### ISSUE TITLE
“智能合约” 文章中的错别字

### ISSUE THREAD

**Issue by tigaliang** [EthFans/wiki#2]
文章第一段：
> “... 发布了白皮书《以太坊：下一代智能合约和去中心话应用平台》...”

中的“去中心话”应为“去中心化”

**Comment by toyab** [comment]
已更正，谢谢指出 ：）

________________________________
发件人: LK <notifications@github.com>
发送时间: 2018年2月27日 9:47:01
收件人: EthFans/wiki
抄送: Subscribed
主题: [EthFans/wiki] “智能合约” 文章中的错别字 (#2)


文章：https://github.com/EthFans/wiki/wiki/%E6%99%BA%E8%83%BD%E5%90%88%E7%BA%A6

文章第一段，“... 发布了白皮书《以太坊：下一代智能合约和去中心话应用平台》...”，“去中心话” 应为 “去中心化”

―
