### ISSUE TITLE
论坛关闭了？

### ISSUE THREAD

**Issue by michaellifly** [EthFans/wiki#5]
https://ethfans.org/posts/blockchain-for-beginners-what-is-blockchain-just-7-step

**Comment by michaellifly** [comment]
3/22晚上好像突然上不了 现在可以了 （美东）

**Comment by Stack165** [comment]
现在又打不开了…怎么回事呢？

**Comment by ronneycjm** [comment]
Hello, I used JPN proxy in mainland and cannot open the website. Any issues?

**Comment by editor-Ajian** [comment]
网站已经关闭了。感谢各位的支持
